### ISSUE TITLE
[TODO] Provide necessary comments

### ISSUE THREAD

**Issue by dorukaks** [dorukaks/TT-ICE#10]
# Description of item

Comment each function so that anyone going to use it understands it

- [ ] Comment DaMAT.py
- [ ] Comment DaMATutils.py

Correspondence: @dorukaks  

Note to the creator: please name the branch according to <branch_type>/<your_name>/<issue_number(s)_that_you_address>
If you address more than 1 issue with one branch, write each number with an underscore like the following: "chore/doruk/1_2"
But don't try to adress too many issues with a single branch!

**Comment by leighton** [comment]
Thanks for discovering this wonderful algorithm @dorukaks! It would also be great to have a canonical, and simple, example from start to finish showing incremental decomposition (e.g. using a multidimensional gaussian or something).

**Comment by dorukaks** [comment]
Thank you so much for the kind comments @leighton! I wanted to have the repository out as quickly as possible for a peer-reviewed submission and therefore skipped the examples portion but you are most certainly right!

We are currently working on 2 different projects using TT-ICE and TT-ICE* as a part of their frameworks. We hope to get those out fairly soon. But I will provide basic scripts (with appropriate comments of course) for the two examples that we have depicted in [our preprint](https://arxiv.org/abs/2211.12487).

If you are looking to use TT-ICE in a project of yours and need help implementing, please don't hesitate to reach out. I'd be more than happy to help!

**Comment by dorukaks** [comment]
Hey @leighton, I (finally) was able to publish some example scripts for TT-ICE and TT-ICE* :smile: . You can check out the [examples](https://github.com/dorukaks/TT-ICE/tree/main/examples) folder. And of course, don't hesitate to ping me if you need any help understanding the scripts!
